# Generated by Django 5.0.7 on 2025-11-01 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, max_length=128)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('alliance_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
