# Generated by Django 5.0.7 on 2025-11-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_evecharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='main_character_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_character_name',
        ),
        migrations.DeleteModel(
            name='EveCharacter',
        ),
    ]
