# Generated by Django 5.0.7 on 2025-11-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_main_character_id_and_more'),
        ('eve_sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_users', to='eve_sso.evecharacter'),
        ),
    ]
