# Generated by Django 5.0.7 on 2025-11-11 22:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=100, unique=True)),
                ('strategic', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('peacetime', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('shitstack', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('tnt_special', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('hull_contract', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ship_name'],
            },
        ),
        migrations.CreateModel(
            name='SRPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_ceiling_peacetime', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_ceiling_strategic', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_calculate_payouts', models.BooleanField(default=True)),
                ('default_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SRPClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STRATEGIC', 'Strategic'), ('PEACETIME', 'Peacetime'), ('SHITSTACK', 'Shitstack'), ('TNT_SPECIAL', 'TNT Special')], max_length=20)),
                ('esi_link', models.URLField(help_text='Killmail/ESI link')),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('broadcast_text', models.TextField(blank=True)),
                ('fit_data', models.JSONField(blank=True, null=True)),
                ('isk_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_srp_claims', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='srp.shippayout')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srp_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='srp.srpclaim')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='srpclaim',
            index=models.Index(fields=['status', 'category'], name='srp_srpclai_status_b9a91a_idx'),
        ),
        migrations.AddIndex(
            model_name='srpclaim',
            index=models.Index(fields=['submitted_at'], name='srp_srpclai_submitt_2be4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='srpclaim',
            index=models.Index(fields=['character_name'], name='srp_srpclai_charact_3309e8_idx'),
        ),
    ]
