# Generated by Django 5.0.7 on 2026-01-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='srpclaim',
            options={'ordering': ['-submitted_at'], 'permissions': [('can_review_srp', 'Can review SRP claims')]},
        ),
    ]
