# Generated by Django 5.0.7 on 2026-01-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0002_alter_srpclaim_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippayout',
            options={'ordering': ['ship_name'], 'permissions': [('can_manage_srp_payouts', 'Can manage SRP payouts')]},
        ),
        migrations.AlterModelOptions(
            name='srpclaim',
            options={'ordering': ['-submitted_at'], 'permissions': [('can_review_srp', 'Can review SRP claims'), ('can_view_srp_reports', 'Can view SRP reports')]},
        ),
    ]
