# Generated by Django 5.0.7 on 2026-01-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0003_alter_shippayout_options_alter_srpclaim_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpclaim',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
