# Generated by Django 5.0.7 on 2026-01-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0004_srpclaim_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpclaim',
            name='killmail_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='killmail_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='killmail_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='ship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='ship_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='solar_system_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='solar_system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='victim_character_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='victim_character_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='broadcast_text',
            field=models.TextField(blank=True, help_text='Fleet broadcast text (required for some categories)'),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='character_name',
            field=models.CharField(help_text='Character name reported by submitter (may differ from victim)', max_length=100),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='esi_link',
            field=models.URLField(help_text='Killmail / ESI link'),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='fit_data',
            field=models.JSONField(blank=True, help_text='Optional ship fitting data (future use)', null=True),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='note',
            field=models.TextField(blank=True, help_text='Latest reviewer note (full history in ClaimReview)'),
        ),
        migrations.AlterField(
            model_name='srpclaim',
            name='ship',
            field=models.ForeignKey(blank=True, help_text='Resolved ShipPayout (manual or ESI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='srp.shippayout'),
        ),
    ]
