# Generated by Django 5.0.7 on 2026-01-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0005_srpclaim_killmail_hash_srpclaim_killmail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpconfig',
            name='blue_alliance_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='srpconfig',
            name='blue_corp_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
