# Generated by Django 5.0.7 on 2026-01-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0006_srpconfig_blue_alliance_ids_srpconfig_blue_corp_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiTypeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type_id'],
            },
        ),
    ]
