# Generated by Django 5.0.7 on 2026-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0008_payoutimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpclaim',
            name='category',
            field=models.CharField(choices=[('STRATEGIC', 'Strategic'), ('PEACETIME', 'Peacetime'), ('SHITSTACK', 'Shitstack'), ('TNT_SPECIAL', 'TNT Special'), ('Manual', 'Manual')], max_length=20),
        ),
    ]
