# Generated by Django 5.0.7 on 2026-01-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0011_srpclaim_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='srpclaim',
            name='fitcheck_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='fitcheck_status',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='fitcheck_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctrineFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('eft_text', models.TextField(help_text='Original EFT text for this fit.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_doctrine_fits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ship_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='fitcheck_best_fit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_claims', to='srp.doctrinefit'),
        ),
        migrations.AddField(
            model_name='srpclaim',
            name='fitcheck_selected_fit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_claims', to='srp.doctrinefit'),
        ),
        migrations.CreateModel(
            name='DoctrineFitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_group', models.CharField(choices=[('HIGH', 'High'), ('MID', 'Mid'), ('LOW', 'Low'), ('RIG', 'Rig')], max_length=10)),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('doctrine_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='srp.doctrinefit')),
            ],
            options={
                'ordering': ['doctrine_fit_id', 'slot_group', 'type_name', 'type_id'],
            },
        ),
        migrations.AddIndex(
            model_name='doctrinefit',
            index=models.Index(fields=['ship_type_id', 'active'], name='srp_doctrin_ship_ty_c30b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctrinefititem',
            index=models.Index(fields=['doctrine_fit', 'slot_group'], name='srp_doctrin_doctrin_22743e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctrinefititem',
            index=models.Index(fields=['type_id'], name='srp_doctrin_type_id_dca137_idx'),
        ),
    ]
