# Generated by Django 5.0.7 on 2026-01-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0012_srpclaim_fitcheck_data_srpclaim_fitcheck_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpclaim',
            name='no_rigs_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
