# Generated by Django 5.0.7 on 2026-01-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0013_srpclaim_no_rigs_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpconfig',
            name='self_alliance_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
