# Generated by Django 5.0.7 on 2026-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0014_srpconfig_self_alliance_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiEntityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=16)),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='srp_esienti_entity__4c81b3_idx')],
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
