# Generated by Django 5.0.7 on 2026-05-08 00:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0015_esientitycache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpclaim',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='srpclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('killmail_id__isnull', False)), fields=('killmail_id', 'killmail_hash'), name='unique_killmail'),
        ),
    ]
